const objc = @import("objc.zig");

pub const Window = extern struct {
    window: objc.c.id,
    view: objc.c.id,
    delegate: objc.c.id,
    cursor: objc.c.id,
    marked_text: objc.c.id,
    layer: objc.c.id,
    monitor: ?*anyopaque,
    should_close: bool,
    maximized: bool,
    occluded: bool,
    resizable: bool,
    decorated: bool,
    floating: bool,
    auto_iconify: bool,
    scale_framebuffer: bool,
    user_pointer: ?*anyopaque,
    callback_id: usize,
    cursor_mode: c_int,
    cursor_warp_delta_x: f64,
    cursor_warp_delta_y: f64,
    virtual_cursor_x: f64,
    virtual_cursor_y: f64,
    video_width: u32,
    video_height: u32,
    video_red_bits: u32,
    video_green_bits: u32,
    video_blue_bits: u32,
    video_refresh_rate: u32,
    min_width: u32,
    min_height: u32,
    max_width: u32,
    max_height: u32,
    aspect_numerator: u32,
    aspect_denominator: u32,
    windowed_x: f64,
    windowed_y: f64,
    windowed_width: f64,
    windowed_height: f64,
    width: f64,
    height: f64,
    fb_width: f64,
    fb_height: f64,
    xscale: f64,
    yscale: f64,
    windowed_style: usize,
    windowed_level: isize,
    windowed_has_shadow: bool,
};

pub const Cursor = extern struct {
    cursor: objc.c.id,
};
