const objc = @import("objc.zig");

pub const Window = extern struct {
    window: objc.c.id,
    view: objc.c.id,
    delegate: objc.c.id,
    cursor: objc.c.id,
    marked_text: objc.c.id,
    monitor: ?*anyopaque,
    should_close: bool,
    maximized: bool,
    resizable: bool,
    decorated: bool,
    floating: bool,
    auto_iconify: bool,
    scale_framebuffer: bool,
    user_pointer: ?*anyopaque,
    callback_id: usize,
    cursor_mode: c_int,
    modifier_flags: usize,
    cursor_warp_delta_x: f64,
    cursor_warp_delta_y: f64,
    virtual_cursor_x: f64,
    virtual_cursor_y: f64,
    windowed_x: f64,
    windowed_y: f64,
    windowed_width: f64,
    windowed_height: f64,
    width: f64,
    height: f64,
    fb_width: f64,
    fb_height: f64,
    xscale: f64,
    yscale: f64,
    windowed_style: usize,
    windowed_level: isize,
    windowed_has_shadow: bool,
};

pub const Cursor = extern struct {
    cursor: objc.c.id,
};
